name: Keyhole
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cudatoolkit=11.0.221
  - cycler=0.10.0
  - freetype=2.10.4
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2020.2
  - jpeg=9b
  - kiwisolver=1.3.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.40.0
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pillow=8.0.1
  - pip=20.3.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytorch=1.7.1
  - qt=5.9.7
  - setuptools=51.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
