name: Keyhole
channels:
  - pytorch
  - defaults
dependencies:
  - _pytorch_select=0.1=cpu_0
  - blas=1.0=mkl
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - freetype=2.10.4
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.3.0
  - libmklml=2019.0.5
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.40.0
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.0.4
  - ninja=1.10.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - pillow=8.0.1
  - pip=20.2.4
  - pycparser=2.20
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytorch=1.7.0
  - qt=5.9.7
  - scipy=1.5.2
  - setuptools=50.3.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - tornado=6.0.4
  - typing_extensions=3.7.4.3
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
